name: p3pch4t
description: p3p chat

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.1+100000

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shelf: ^1.4.0
  shelf_router: ^1.1.3
  openpgp: ^3.5.1
  shared_preferences: ^2.0.17
  objectbox: ^1.7.2
  path_provider: ^2.0.12
  path: ^1.8.2
  http: ^0.13.5
  random_string: ^2.3.1
  objectbox_flutter_libs: any
  flutter_background_service: ^2.4.6
  flutter_local_notifications: ^13.0.0
  file_picker: ^5.2.5
  async: ^2.10.0
  crypto: ^3.0.2
  convert: ^3.1.1
  filesize: ^2.0.1
  permission_handler: ^10.2.0
  i2p_flutter:
    path: ../i2p_flutter
  dio: ^5.0.1 
  mime: ^1.0.4
  markdown: ^7.0.1
  flutter_markdown: ^0.6.14
  pretty_qr_code: ^2.0.3
  qr: ^3.0.1
  open_filex: ^4.3.2
  flutter_zxing: ^1.1.0
  mobile_scanner: ^3.0.0
  flex_color_picker: ^3.1.0
  flutter_svg: ^2.0.2
  select_dialog: ^2.0.0
  cross_file: ^0.3.3+4
  share_plus: ^6.3.1
  duration: ^3.0.12
  url_launcher: ^6.1.10
  table_calendar: ^3.0.9
  date_format: ^2.0.7
  flutter_expandable_fab: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
 
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  objectbox_generator: any

flutter:
  uses-material-design: true

  assets:
    - assets/backgrounds/
    - assets/images/help/
    - packages/openpgp/web/assets/worker.js
    - packages/openpgp/web/assets/wasm_exec.js
    - packages/openpgp/web/assets/openpgp.wasm
